# Generated by Django 3.0 on 2020-02-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info',
            name='Steps',
        ),
    ]
