# Generated by Django 3.0 on 2020-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='UNKNOWN', max_length=100)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=100)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Setup', models.CharField(blank=True, max_length=100)),
                ('NoOfTCsPassed', models.IntegerField(blank=True, null=True)),
                ('E2EFocus', models.CharField(blank=True, default='NOT ENTERED', max_length=100)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='UNKNOWN', max_length=100)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=100)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Setup', models.CharField(blank=True, max_length=100)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='UNKNOWN', max_length=100)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=100)),
                ('Setup', models.CharField(blank=True, max_length=100)),
                ('CfgFileUsed', models.CharField(blank=True, max_length=100)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Notes', models.TextField()),
            ],
        ),
    ]
