# Generated by Django 3.0 on 2020-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0002_e2e_longevity_stress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2e',
            name='Bugs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='e2e',
            name='Build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='e2e',
            name='E2EFocus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='e2e',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e2e',
            name='Result',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='e2e',
            name='Setup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
