# Generated by Django 3.0 on 2020-02-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0002_remove_tc_info_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='Steps',
            field=models.TextField(blank=True, default='NO STEPS PROVIDED'),
        ),
    ]
