# Generated by Django 3.0 on 2020-02-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0005_auto_20200212_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2e',
            old_name='Setup',
            new_name='CardType',
        ),
        migrations.RenameField(
            model_name='longevity',
            old_name='Setup',
            new_name='CardType',
        ),
        migrations.RenameField(
            model_name='stress',
            old_name='Setup',
            new_name='CardType',
        ),
    ]
