# Generated by Django 2.2.7 on 2020-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_info',
            name='Scenario',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=200),
        ),
    ]
