# Generated by Django 2.2.7 on 2020-01-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0002_auto_20200107_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='QARateOfProgress',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
