# Generated by Django 2.2.7 on 2019-12-18 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0003_releases_engineercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='UpgradeMetrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
