# Generated by Django 2.2.7 on 2020-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0003_auto_20200114_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='QAStartDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
