# Generated by Django 2.2.7 on 2020-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0004_auto_20200114_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='ActualReleaseDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='TargetedCodeFreezeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='TargetedReleaseDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='UpgradeTestingStartDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
