# Generated by Django 2.2.7 on 2020-01-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0005_auto_20200114_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='ActualReleaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='QAStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='TargetedCodeFreezeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='TargetedReleaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='UpgradeTestingStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
