# Generated by Django 2.2.7 on 2020-01-16 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0006_auto_20200114_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='CardType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='releases',
            name='FinalBuild',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='releases',
            name='FinalDockerCore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='releases',
            name='FinalOS',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='releases',
            name='ServerType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='releases',
            name='SetupsUsed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='releases',
            name='UpgradeMetrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
