# Generated by Django 2.2.7 on 2020-01-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0007_auto_20200116_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='Designation',
        ),
        migrations.AddField(
            model_name='tc_info',
            name='Priority',
            field=models.CharField(blank=True, default='P4', max_length=3),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
