# Generated by Django 2.2.7 on 2020-01-17 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0008_auto_20200116_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='BuildNumberList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='CardType',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
