# Generated by Django 2.2.7 on 2020-01-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0009_auto_20200117_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_status',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
