# Generated by Django 3.0 on 2020-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='CardType',
            field=models.CharField(blank=True, default='NO CARD PROVIDED', max_length=100),
        ),
        migrations.AddField(
            model_name='logs',
            name='TcID',
            field=models.CharField(blank=True, default='NO ID PROVIDED', max_length=200),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='BloodGroup',
            field=models.CharField(blank=True, choices=[('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='City',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='DateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='DateOfJoining',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='EmenrgencyContactPersonName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='EmergencyCOntactPersonRelation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='EmergencyContactNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='PersonalEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='PinCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='PreviousCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='PreviousWorkExperienceInMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='State',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='TShirtSize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Description',
            field=models.TextField(blank=True, default='NO DESCRIPTION PROVIDED'),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Domain',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='ExpectedBehaviour',
            field=models.CharField(blank=True, default='NO EXPECTED BEHAVIOUR PROVIDED', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Notes',
            field=models.CharField(blank=True, default='NO NOTES PROVIDED', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Priority',
            field=models.CharField(blank=True, default='P4', max_length=5),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='SubDomain',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='TcName',
            field=models.CharField(blank=True, default='NOT AUTOMATED', max_length=2000),
        ),
    ]
