# Generated by Django 3.0 on 2020-01-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0002_auto_20200130_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_info',
            old_name='Status',
            new_name='WorkingStatus',
        ),
    ]
