# Generated by Django 3.0 on 2020-01-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0003_auto_20200130_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='UserName',
            new_name='email',
        ),
    ]
