# Generated by Django 3.0 on 2020-01-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0005_auto_20200131_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='Role',
            new_name='role',
        ),
    ]
